#pragma once

#include <QObject>

class CanvasWidgetTest : public QObject {
    Q_OBJECT

private slots:
    void sizeHintFallsBackWithNoProject();
    void sizeHintMatchesProjectCanvasDimensions();
    void rendersALayersContentInsteadOfThePlaceholder();
    void skipsAHiddenTopmostLayerInFavorOfTheOneBelowIt();
    void reflectsALayersTranslationColumns();
    void drawsAPlayheadLineAtTheGivenFraction();
    void drawsNoPlayheadByDefault();
    void toolModeDefaultsToNone();
    void setToolModeChangesTheMode();
    void mousePressDoesNothingInNoneMode();
    void mousePressInPaintModeEmitsPaintStrokeStartedWithAConvertedPoint();
    void mouseMoveWithoutAPriorPressDoesNothingInPaintMode();
    void mouseMoveAfterPressEmitsPaintStrokeContinued();
    void mouseReleaseEmitsPaintStrokeEndedAndEndsTheStroke();
    void changingToolModeAwayFromPaintCancelsAnyActiveStroke();
    void setPaintPreviewPathDrawsItOverTheCanvas();
    void setPaintPreviewPathWithNoNodesDrawsNothing();
    void setPreviewSelectedNodeIndexHighlightsThatNodeDistinctly();
    void showBoundingBoxesDrawsNothingWhenOff();
    void showBoundingBoxesDrawsAnActiveOperationsBoundingBox();
    void showPathGeometryDrawsAnActiveOperationsPath();
    void mouseMoveEmitsCursorMovedRegardlessOfToolMode();
    void leavingTheCanvasEmitsCursorLeft();
    void mousePressInPickModeEmitsPickStrokeStartedWithAConvertedPoint();
    void mouseMoveAfterPressInPickModeEmitsPickStrokeContinued();
    void mouseReleaseInPickModeEmitsPickStrokeEndedAndEndsTheGesture();
    void changingToolModeAwayFromPickCancelsAnyActiveGesture();
    void setPickSelectionBoundsDrawsAHighlight();
    void setPickSelectionBoundsIsHiddenWhileALivePreviewIsShowing();
    void setPickSelectionBoundsWithNoValueDrawsNothing();
    void mousePressInSelectModeEmitsSelectStrokeStartedWithAConvertedPoint();
    void mousePressInSelectModeEmitsSelectStrokeStartedWithTheModifiersHeld();
    void mouseMoveAfterPressInSelectModeEmitsSelectStrokeContinued();
    void mouseReleaseInSelectModeEmitsSelectStrokeEndedAndEndsTheGesture();
    void changingToolModeAwayFromSelectCancelsAnyActiveGesture();
    void setSelectionBoundsDrawsAHighlight();
    void setSelectionBoundsWithNoValueDrawsNothing();
    void setSelectionHasMaskShapeStillDrawsTheRectangleDashed();
    void mousePressInPathModeEmitsPathNodePlacedWithAConvertedPoint();
    void mouseMoveAfterPressInPathModeDoesNotEmitPathNodePlacedAgain();
    void mouseReleaseInPathModeDoesNotEmitPathNodePlacedAgain();
    void setVerticalAxisLabelModeChangesWhatsDrawnNearTheLeftEdge();
    void setHorizontalAxisLabelModeChangesWhatsDrawnNearTheBottomEdge();
    void setFrequencyGridConfigDrawsHorizontalLines();
    void setTimingGridConfigDrawsVerticalLines();
    void freshWidgetIsInFitToWindowMode();
    void zoomInSwitchesToManualAndScalesBothAxesByTheNormalStep();
    void zoomOutSwitchesToManualAndScalesBothAxesByTheNormalStep();
    void zoomInTimeOnlyLeavesTheFrequencyAxisAtItsCurrentEffectiveSize();
    void zoomInFrequencyOnlyLeavesTheTimeAxisAtItsCurrentEffectiveSize();
    void zoomInCoarseUsesABiggerStepThanZoomIn();
    void zoomToActualSizeSetsOnePixelPerColumnAndBin();
    void zoomToFitReturnsToFitToWindowMode();
    void zoomModeChangedEmitsOnlyOnAnActualModeTransition();
    void settingANewProjectResetsZoomToFitToWindow();
    void wheelWithNoModifierDoesNotZoom();
    void wheelWithCtrlZoomsCoarseProportionally();
    void wheelWithAltZoomsFrequencyOnly();
    void wheelWithAltAndAHorizontalOnlyDeltaStillZoomsFrequencyOnly();
    void wheelWithShiftZoomsTimeOnly();
    void wheelScrollingDownZoomsOut();
    void setMindWavePreviewDrawsASemiTransparentGrayscaleOverlay();
    void setMindWavePreviewWithNulloptClearsIt();
    void settingANewProjectClearsTheMindWavePreview();
    void chordPreviewIsHiddenByDefaultEvenWithDataSet();
    void chordPreviewShowsWhenTheChordGeneratorPanelIsVisible();
    void chordPreviewShowsWhenTheChordStampToolIsActive();
    void chordPreviewHidesAgainOnceNeitherConditionHolds();
    void selectionHighlightHidesWhenNeitherPickNorSelectIsActive();
    void selectionHighlightShowsWithPickToolActive();
    void selectionHighlightHidesAgainOnceSwitchingAwayFromSelectOrPick();
    void selectionBoundaryHighlightAlsoHidesWhenNeitherPickNorSelectIsActive();

    // Sound Flower (v0.Y.53.1).
    void polarModeDefaultsToFalse();
    void setPolarModeChangesPolarMode();
    void polarModeCentrePointConvertsToTimeZeroAndTheLowestFrequency();
    void polarModeTopEdgeConvertsToTimeZeroAndTheHighestFrequency();
    void polarModeAQuarterTurnClockwiseConvertsToAQuarterOfTheWayThroughTime();
    void polarModeOutsideTheDiskConvertsToNullopt();
    void polarModePaintPressInsideTheDiskEmitsPaintStrokeStarted();
    void polarModePaintPressOutsideTheDiskEmitsNothing();
};
